version: '3'
services:
  # database
  mysql:
    image: mysql:5.7.16
    ports:
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql/data, but will be ignored to Git
      - ./mysql/data:/var/lib/mysql
      - ./mysql/schemes:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  # memcached
  memcached:
    image: memcached:1.5.3
    ports:
      - "11211:11211"

  # php-fpm
  php-fpm:
    build: ./php-fpm
    working_dir: /usr/share/nginx/html
    ports:
      - "9000"
    volumes:
      - ${WWW_DIR}:/usr/share/nginx/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment: 
      - WWW_DIR=/usr/share/nginx/html
    depends_on:
      - mysql

  # web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ${WWW_DIR}:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # nginx SSL
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - php-fpm
